from events.event import Event
from admin_api.patient_data_import import PatientDataRow
import json


def get_field(data, field):
    if data.get(field) is None:
        return None
    return 'Yes' if data.get(field) else 'No'

def get_text_field(data, field, text_field):
    if data.get(field) is None:
        return None
    if data.get(field) is not None and not data.get(text_field):
        return 'Yes' if data.get(field) else 'No'
    return data.get(text_field) if data.get(field) else 'No'

def write_vitals_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.heart_rate = data.get('heartRate')
    if data.get('systolic') and data.get('diastolic'):
        row.blood_pressure = f"{data.get('systolic')}/{data.get('diastolic')}"
    row.sats = data.get('sats')
    row.temp = data.get('temp')
    row.respiratory_rate = data.get('respiratoryRate')
    row.weight = data.get('weight')
    row.blood_glucose = data.get('bloodGlucose')

def write_medical_hx_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.allergies = data.get('allergies')
    row.surgery_hx = data.get('surgeryHx')
    row.chronic_conditions = data.get('chronicConditions')
    row.current_medications = data.get('currentMedications')
    row.vaccinations = data.get('vaccinations')

def write_examination_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.examination = data.get('examination')
    row.general_observations = data.get('generalObservations')
    row.diagnosis = data.get('diagnosis')
    row.treatment = data.get('treatment')
    row.covid_19 = get_field(data, 'covid19')
    row.referral = get_text_field(data, 'referral', 'referralText')

def write_med1_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_1 = data.get('medication')
    row.type_1 = data.get('type')
    row.dosage_1 = data.get('dosage')
    row.days_1 = data.get('days')

def write_med2_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_2 = data.get('medication')
    row.type_2 = data.get('type')
    row.dosage_2 = data.get('dosage')
    row.days_2 = data.get('days')

def write_med3_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_3 = data.get('medication')
    row.type_3 = data.get('type')
    row.dosage_3 = data.get('dosage')
    row.days_3 = data.get('days')
		
def write_med4_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_4 = data.get('medication')
    row.type_4 = data.get('type')
    row.dosage_4 = data.get('dosage')
    row.days_4 = data.get('days')

def write_med5_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.medication_5 = data.get('medication')
    row.type_5 = data.get('type')
    row.dosage_5 = data.get('dosage')
    row.days_5 = data.get('days')

def write_physiotherapy_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.previous_treatment = get_text_field(data, 'previousTreatment', 'previousTreatmentText')
    row.complaint_p = data.get('complaint')
    row.findings = data.get('findings')
    row.treatment_plan = data.get('treatmentPlan')
    row.treatment_session = data.get('treatmentSession')
    row.recommendations = data.get('recommendations')
    row.referral = get_text_field(data, 'referral', 'referralText')

def write_covid_19_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    if data.get('seekCare'):
        row.covid_19_result = 'Seek Emergency Care and Isolate'
    elif data.get('testAndIsolate'):
        row.covid_19_result = 'Test/Isolate Patient'  
    else:
        row.covid_19_result = 'No Action Necessary'

def write_emergency_attention_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.dateTimeEmergency = data.get('dateTime')
    row.namesEmergency = data.get('names')
    row.surnamesEmergency = data.get('surnames')
    row.occupationEmergency = data.get('occupation')
    row.addressEmergency = data.get('address')
    row.phoneNumberEmergency = data.get('phoneNumber')
    row.idEmergency = data.get('id')
    row.arrivesInEmergency = data.get('arrivesIn')
    row.accidentCausesEmergency = data.get('accidentCauses')
    row.accidentPlaceEmergency = data.get('accidentPlace')
    row.weightEmergency = data.get('weight')
    row.sizeEmergency = data.get('size')
    row.temperatureEmergency = data.get('temperature')
    row.bloodPressureEmergency = data.get('bloodPressure')
    row.heartRateEmergency = data.get('heartRate')
    row.breathingFrequencyEmergency = data.get('breathingFrequency')
    row.oxygenSaturationEmergency = data.get('oxygenSaturation')
    row.attentionDateHoursEmergency = data.get('attentionDateHours')
    row.attendantNameEmergency = data.get('attendantName')
    row.notifyToNameEmergency = data.get('notifyToName')
    row.notifyToRelationshipEmergency = data.get('notifyToRelationship')
    row.notifyToaddressEmergency = data.get('notifyToaddress')
    row.notifyTophoneEmergency = data.get('notifyTophone')
    row.personalMedicalHistoryEmergency = data.get('personalMedicalHistory')
    row.allergiesEmergency = data.get('allergies')
    row.reasonForConsultationEmergency = data.get('reasonForConsultation')
    row.clinicalSummaryEmergency = data.get('clinicalSummary')
    row.physicalExamEmergency = data.get('physicalExam')
    row.evaluationEmergency = data.get('evaluation')
    row.diagnosisEmergency = data.get('diagnosis')
    row.feedingEmergency = data.get('feeding')
    row.medicinesEmergency = data.get('medicines')
    row.examsEmergency = data.get('exams')
    row.normsOrRecommendationsEmergency = data.get('normsOrRecommendations')
    row.destinyEmergency = data.get('destiny')
    row.emergencyTypeEmergency = data.get('emergencyType')
    row.treatingPhysicianSignatureEmergency = data.get('treatingPhysicianSignature')

def write_subsequent_evolution_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.nameSurnameEvolution = data.get('nameSurname')
    row.idEvolution = data.get('id')
    row.communityEvolution = data.get('community')
    row.proceedingsEvolution = data.get('proceedings')
    row.dateTimeEvolution = data.get('dateTime')
    row.bloodPressureEvolution = data.get('bloodPressure')
    row.heartRateEvolution = data.get('heartRate')
    row.breathingFrequencyEvolution = data.get('breathingFrequency')
    row.temperatureEvolution = data.get('temperature')
    row.oxygenSaturationEvolution = data.get('oxygenSaturation')
    row.weightEvolution = data.get('weight')
    row.sizeEvolution = data.get('size')
    row.consultationReasonEvolution = data.get('consultationReason')
    row.illnessHistoryEvolution = data.get('illnessHistory')
    row.objectiveEvolution = data.get('objective')
    row.evaluationEvolution = data.get('evaluation')
    row.diagnosisEvolution = data.get('diagnosis')
    row.feedingEvolution = data.get('feeding')
    row.medicinesEvolution = data.get('medicines')
    row.examsEvolution = data.get('exams')
    row.normsOrRecommendationsEvolution = data.get('normsOrRecommendations')
    row.treatingPhysicianEvolution = data.get('treatingPhysician')
    row.minsaCodeEvolution = data.get('minsaCode')

def write_nursing_note_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.nameSurnameNursing = data.get('nameSurname')
    row.idNursing = data.get('id')
    row.communityNursing = data.get('community')
    row.proceedingsNursing = data.get('proceedings')
    row.dateTimeNursing = data.get('dateTime')
    row.noteNursing = data.get('note')
    row.nurseNameNursing = data.get('nurseName')
    row.minsaCodeNursing = data.get('minsaCode')

def write_ultrasound_consultation_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.dateUltrasound = data.get('date')
    row.namesUltrasound = data.get('names')
    row.surnameUltrasound = data.get('surname')
    row.idUltrasound = data.get('id')
    row.originUltrasound = data.get('origin')
    row.ultrasoundPerformedUltrasound = data.get('ultrasoundPerformed')
    row.resourceUltrasound = data.get('resource')
    row.minsaCodeUltrasound = data.get('minsaCode')

def write_laboratory_consultation_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.dateLaboratory = data.get('date')
    row.namesLaboratory = data.get('names')
    row.surnameLaboratory = data.get('surname')
    row.idLaboratory = data.get('id')
    row.originLaboratory = data.get('origin')
    row.testPerformedLaboratory = data.get('testPerformed')
    row.resourceLaboratory = data.get('resource')
    row.minsaCodeLaboratory = data.get('minsaCode')

def write_odontology_consultation_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.dateOdontology = data.get('date')
    row.namesOdontology = data.get('names')
    row.surnameOdontology = data.get('surname')
    row.idOdontology = data.get('id')
    row.originOdontology = data.get('origin')
    row.procedurePerformedOdontology = data.get('procedurePerformed')
    row.resourceOdontology = data.get('resource')
    row.minsaCodeOdontology = data.get('minsaCode')

def write_family_pathological_history_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.arterialHypertensionFamily = data.get('arterialHypertension')
    row.diabetesMellitusFamily = data.get('diabetesMellitus')
    row.tuberculosisFamily = data.get('tuberculosis')
    row.cancerFamily = data.get('cancer')
    row.epilepsyFamily = data.get('epilepsy')
    row.heartDiseasesFamily = data.get('heartDiseases')
    row.nephropathiesFamily = data.get('nephropathies')
    row.liverDiseasesFamily = data.get('liverDiseases')
    row.mentalDiseasesFamily = data.get('mentalDiseases')
    row.othersFamily = data.get('others')
    row.specifyFamily = data.get('specify')

def write_socioeconomic_situation_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.house = data.get('house')
    row.walls = data.get('walls')
    row.flat = data.get('flat')
    row.ceiling = data.get('ceiling')
    row.bedrooms = data.get('bedrooms')
    row.animals = data.get('animals')
    row.animalsAndQuantity = data.get('animalsAndQuantity')
    row.waterSource = data.get('waterSource')
    row.electricPower = data.get('electricPower')
    row.toilet = data.get('toilet')
    row.latrine = data.get('latrine')
    row.kitchen = data.get('kitchen')
    row.children_0_5 = data.get('children_0_5')
    row.children_6_10 = data.get('children_6_10')
    row.children_11_15 = data.get('children_11_15')
    row.adults = data.get('adults')
    row.seniors = data.get('seniors')
    row.women = data.get('women')
    row.men = data.get('men')
    row.peopleWorkingNumber = data.get('peopleWorkingNumber')

def write_pathological_history_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.childhoodDiseasesAdultPathological = data.get('childhoodDiseases')
    row.cardiovascularAdultPathological = data.get('cardiovascular')
    row.customizedAllergiesAdultPathological = data.get('customizedAllergies')
    row.pulmonaryAdultPathological = data.get('pulmonary')
    row.chronicDiseasesAdultPathological = data.get('chronicDiseases')
    row.transfusionsAdultPathological = data.get('transfusions')
    row.sexuallyTransmittedInfectionsAdultPathological = data.get('sexuallyTransmittedInfections')
    row.digestiveAdultPathological = data.get('digestive')
    row.surgicalAdultPathological = data.get('surgical')
    row.hospitalizationsAdultPathological = data.get('hospitalizations')
    row.othersAdultPathological = data.get('others')
    row.specifyAdultPathological = data.get('specify')

def write_non_pathological_history_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.alcoholismActive = data.get('alcoholismActive')
    row.alcoholismAgeOfOnset = data.get('alcoholismAgeOfOnset')
    row.alcoholismAgeOfTermination = data.get('alcoholismAgeOfTermination')
    row.alcoholismFrequency = data.get('alcoholismFrequency')
    row.alcoholismAmount = data.get('alcoholismAmount')
    row.alcoholismTypeOfLiquor = data.get('alcoholismTypeOfLiquor')
    row.smokingActive = data.get('smokingActive')
    row.smokingStartAge = data.get('smokingStartAge')
    row.smokingEndAge = data.get('smokingEndAge')
    row.smokingCigarettesNumber = data.get('smokingCigarettesNumber')
    row.drugsActive = data.get('drugsActive')
    row.drugsAgeOfOnset = data.get('drugsAgeOfOnset')
    row.drugsAgeOfTermination = data.get('drugsAgeOfTermination')
    row.drugsFrequency = data.get('drugsFrequency')
    row.drugsType = data.get('drugsType')

def write_gynecological_background_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.menarche = data.get('menarche')
    row.sexualLifeBeginning = data.get('sexualLifeBeginning')
    row.sexualPartnersNum = data.get('sexualPartnersNum')
    row.familyPlanning = data.get('familyPlanning')
    row.lastMenstrualPeriodDate = data.get('lastMenstrualPeriodDate')
    row.currentPregnancy = data.get('currentPregnancy')
    row.weeksOfAmenorrhea = data.get('weeksOfAmenorrhea')
    row.estimatedDueDate = data.get('estimatedDueDate')
    row.lastDeliveryDate = data.get('lastDeliveryDate')
    row.pregnanciesNumber = data.get('pregnanciesNumber')
    row.births = data.get('births')
    row.caesareanSection = data.get('caesareanSection')
    row.abortions = data.get('abortions')
    row.curettage = data.get('curettage')

def write_physical_exploration_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.bloodPressurePhysicalExploration = data.get('bloodPressure')
    row.heartRatePhysicalExploration = data.get('heartRate')
    row.respiratoryRatePhysicalExploration = data.get('respiratoryRate')
    row.temperaturePhysicalExploration = data.get('temperature')
    row.oxygenSaturationPhysicalExploration = data.get('oxygenSaturation')
    row.weightPhysicalExploration = data.get('weight')
    row.heightPhysicalExploration = data.get('height')
    row.bodyMassIndexPhysicalExploration = data.get('bodyMassIndex')
    row.consultationReasonPhysicalExploration = data.get('consultationReason')
    row.illnessHistoryPhysicalExploration = data.get('illnessHistory')
    row.headPhysicalExploration = data.get('head')
    row.eyesPhysicalExploration = data.get('eyes')
    row.earsNoseMouthPhysicalExploration = data.get('earsNoseMouth')
    row.neckPhysicalExploration = data.get('neck')
    row.chestPhysicalExploration = data.get('chest')
    row.heartPhysicalExploration = data.get('heart')
    row.lungFieldsPhysicalExploration = data.get('lungFields')
    row.abdomenPhysicalExploration = data.get('abdomen')
    row.genitalsPhysicalExploration = data.get('genitals')
    row.skeletalMusclePhysicalExploration = data.get('skeletalMuscle')
    row.extremitiesPhysicalExploration = data.get('extremities')
    row.neurologicalPhysicalExploration = data.get('neurological')
    row.evaluationPhysicalExploration = data.get('evaluation')
    row.diagnosisPhysicalExploration = data.get('diagnosis')
    row.feedingPhysicalExploration = data.get('feeding')
    row.medicinesPhysicalExploration = data.get('medicines')
    row.examsPhysicalExploration = data.get('exams')
    row.normsOrRecommendationsPhysicalExploration = data.get('normsOrRecommendations')
    row.treatingPhysicianPhysicalExploration = data.get('treatingPhysician')
    row.minsaCodePhysicalExploration = data.get('minsaCode')

def write_adult_immunizations_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.pneumococcusAdultImmunizations = data.get('pneumococcus')
    row.influenzaAdultImmunizations = data.get('influenza')
    row.tetanusAdultImmunizations = data.get('tetanus')
    row.hepatitisBAdultImmunizations = data.get('hepatitisB')
    row.covidAdultImmunizations = data.get('covid')
    row.tbAdultImmunizations = data.get('tb')
    row.othersAdultImmunizations = data.get('others')

def write_postatal_history_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.apgar = data.get('apgar')
    row.weightInGrams = data.get('weightInGrams')
    row.sizeInCentimeters = data.get('sizeInCentimeters')
    row.suffocation = data.get('suffocation')
    row.suffocationSpecify = data.get('suffocationSpecify')
    row.roomingIn = data.get('roomingIn')
    row.hospitalization = data.get('hospitalization')

def write_feeding_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.exclusiveBreastfeeding = data.get('exclusiveBreastfeeding')
    row.durationOfExclusiveBreastfeeding = data.get('durationOfExclusiveBreastfeeding')
    row.mixedBreastfeeding = data.get('mixedBreastfeeding')
    row.mixedBreastfeedingDuration = data.get('mixedBreastfeedingDuration')
    row.ablactation = data.get('ablactation')

def write_immunization_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.bcgDose1 = data.get('bcgDose1')
    row.pentavalentDose1 = data.get('pentavalentDose1')
    row.pentavalentDose2 = data.get('pentavalentDose2')
    row.pentavalentDose3 = data.get('pentavalentDose3')
    row.polioDose1 = data.get('polioDose1')
    row.polioDose2 = data.get('polioDose2')
    row.polioDose3 = data.get('polioDose3')
    row.polioReinforcement = data.get('polioReinforcement')
    row.polioReinforcementDoses = data.get('polioReinforcementDoses')
    row.rotavirusDose1 = data.get('rotavirusDose1')
    row.rotavirusDose2 = data.get('rotavirusDose2')
    row.rotavirusDose3 = data.get('rotavirusDose3')
    row.mmrDose1 = data.get('mmrDose1')
    row.dptReinforcement = data.get('dptReinforcement')
    row.dptReinforcementDoses = data.get('dptReinforcementDoses')
    row.dtDose1 = data.get('dtDose1')
    row.dtDose2 = data.get('dtDose2')
    row.dtReinforcement = data.get('dtReinforcement')
    row.dtReinforcementDoses = data.get('dtReinforcementDoses')

def write_psychomotor_development_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.suckVigorously = data.get('suckVigorously')
    row.handsClosed = data.get('handsClosed')
    row.flexArms = data.get('flexArms')
    row.moorishReflex = data.get('moorishReflex')
    row.vocalize = data.get('vocalize')
    row.alternateLegMovement = data.get('alternateLegMovement')
    row.openHands = data.get('openHands')
    row.socialSmile = data.get('socialSmile')
    row.lookAtMothers = data.get('lookAtMothers')
    row.followObjects = data.get('followObjects')
    row.reactToSound = data.get('reactToSound')
    row.raiseHead = data.get('raiseHead')
    row.grabObjects = data.get('grabObjects')
    row.makeSounds = data.get('makeSounds')
    row.holdsHead = data.get('holdsHead')
    row.takeToy = data.get('takeToy')
    row.bringsObjectsToMouth = data.get('bringsObjectsToMouth')
    row.locateSound = data.get('locateSound')
    row.turnTowardsObject = data.get('turnTowardsObject')
    row.playDiscover = data.get('playDiscover')
    row.objectsPassed = data.get('objectsPassed')
    row.sitsAlone = data.get('sitsAlone')
    row.doubleSyllables = data.get('doubleSyllables')
    row.imitateGestures = data.get('imitateGestures')
    row.topPliers = data.get('topPliers')
    row.confusingWords = data.get('confusingWords')
    row.walkWithSupport = data.get('walkWithSupport')
    row.gesturesOnDemand = data.get('gesturesOnDemand')
    row.placeCubes = data.get('placeCubes')
    row.sayWord = data.get('sayWord')
    row.walkWithoutSupport = data.get('walkWithoutSupport')
    row.identifyTwoObjects = data.get('identifyTwoObjects')
    row.scribbles = data.get('scribbles')
    row.saysThreeWords = data.get('saysThreeWords')
    row.walkBackwards = data.get('walkBackwards')
    row.takesOffClothes = data.get('takesOffClothes')
    row.towerFiveCubes = data.get('towerFiveCubes')
    row.saysShortSentences = data.get('saysShortSentences')
    row.kickBall = data.get('kickBall')
    row.feedsItself = data.get('feedsItself')
    row.saysLongSentences = data.get('saysLongSentences')
    row.dressesAlone = data.get('dressesAlone')
    row.complexOrders = data.get('complexOrders')

def write_pediatric_pathological_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.infections = data.get('infections')
    row.chronicDiseases = data.get('chronicDiseases')
    row.surgeries = data.get('surgeries')
    row.allergies = data.get('allergies')
    row.hospitalizations = data.get('hospitalizations')
    row.others = data.get('others')

def write_pediatric_physical_event(row: PatientDataRow, event):
    data = json.loads(event.event_metadata)
    row.bloodPressurePediatricPhysical = data.get('bloodPressure')
    row.heartRatePediatricPhysical = data.get('heartRate')
    row.breathingFrequencyPediatricPhysical = data.get('breathingFrequency')
    row.silvermanAndersonPediatricPhysical = data.get('silvermanAnderson')
    row.oxygenSaturationPediatricPhysical = data.get('oxygenSaturation')
    row.weightPediatricPhysical = data.get('weight')
    row.sizeLengthPediatricPhysical = data.get('sizeLength')
    row.headCircunferencePediatricPhysical = data.get('headCircunference')
    row.chestCircumferencePediatricPhysical = data.get('chestCircumference')
    row.abdominalPerimeterPediatricPhysical = data.get('abdominalPerimeter')
    row.bodySurfaceAreaPediatricPhysical = data.get('bodySurfaceArea')
    row.bodyMassIndexPediatricPhysical = data.get('bodyMassIndex')
    row.attendsNameSignPediatricPhysical = data.get('attendsNameSign')
    row.consultationReasonPediatricPhysical = data.get('consultationReason')
    row.illnessHistoryPediatricPhysical = data.get('illnessHistory')
    row.headPediatricPhysical = data.get('head')
    row.eyesPediatricPhysical = data.get('eyes')
    row.earsNoseMouthPediatricPhysical = data.get('earsNoseMouth')
    row.neckPediatricPhysical = data.get('neck')
    row.chestPediatricPhysical = data.get('chest')
    row.heartPediatricPhysical = data.get('heart')
    row.lungFieldsPediatricPhysical = data.get('lungFields')
    row.abdomenPediatricPhysical = data.get('abdomen')
    row.genitalsPediatricPhysical = data.get('genitals')
    row.skeletalMusclePediatricPhysical = data.get('skeletalMuscle')
    row.extremitiesPediatricPhysical = data.get('extremities')
    row.neurologicalPediatricPhysical = data.get('neurological')
    row.evaluationPediatricPhysical = data.get('evaluation')
    row.diagnosisPediatricPhysical = data.get('diagnosis')
    row.feedingPediatricPhysical = data.get('feeding')
    row.medicinesPediatricPhysical = data.get('medicines')
    row.examsPediatricPhysical = data.get('exams')
    row.normsOrRecommendationsPediatricPhysical = data.get('normsOrRecommendations')
    row.treatingPhysicianPediatricPhysical = data.get('treatingPhysician')
    row.minsaCodePediatricPhysical = data.get('minsaCode')